config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  delete 'doses/:id', to: 'doses#destroy', as: :delete_dose
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
     params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(cocktail_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
     params.require(:dose).permit(:description, :ingredient_id)
  end

  def cocktail_params
     params.require(:cocktail_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h1>List of cocktails</h1>
</div>

<div class="container">
  <div class="flex-div">
    <% @cocktails.each do |c| %>
      <div>
        <h5 class= "cocktail-label">
          <%= c[:name] %>
        </h5>
        <%= link_to cocktail_path(c[:id]) do %>
          <div class="cocktail-card" style="background-image: url('<%= cl_image_path c.photo.key %>')">
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

<%= link_to 'Add a new cocktail', new_cocktail_path, class: "btn btn-primary" %>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="table-div">
    <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
   <%= f.input :photo, as: :file %>
  <%= f.submit "Add", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>




<%= link_to 'Back to list', cocktails_path, class: "btn btn-secondary" %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<div class="container">
  <div class="cocktail-img-div" style="background-image: url('<%= cl_image_path @cocktail.photo.key %>')">
  </div>
  <div class="table-div">
    <table class="table">
      <tr>
        <th>Dose</th>
        <th>Ingredient</th>
      </tr>
      <% @cocktail.doses.each do |dose| %>
      <tr>
        <td>
          <%= dose.description %>
        </td>
        <td>
          <%= dose.ingredient.name %>
          <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe,
          delete_dose_path(dose),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
        </td>
      <% end %>
    </table>
  </div>
</div>

<p><%= link_to 'Add a dose to this cocktail', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %></p>


<%= link_to 'Back to list', cocktails_path, class: "btn btn-secondary" %>

app/views/doses/new.html.erb
<h1>Add dose to <%= @cocktail.name %></h1>

<h2>Existing doses</h2>
<div class="container table-div">
  <table class="table">
    <tr>
      <th>Dose</th>
      <th>Ingredient</th>
    </tr>
    <% @cocktail.doses.each do |dose| %>
    <tr>
      <td>
        <%= dose.description %>
      </td>
      <td>
        <%= dose.ingredient.name %>
      </td>
    </tr>
    <% end %>
  </table>
  <div>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all.order('name ASC') %>
  <%= f.submit "Add", class: "btn btn-primary" %>
  <% end %>
</div>
</div>

<%= link_to "Back to cocktail", cocktail_path(@cocktail), class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/7eb72c383f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="body">
      <%= yield %>
    </div>
  </body>
</html>